secure: "dSt4U+PbqwH0f9/7ppjXYHl1L9PxTOYSr3sYzFQIhFV6iDhjSSn4IyAl7KqJUYr9lNDBEpE7bMzmfNq6mchdwjybfXuaHMfC/5d8M6ml7L7ML1t9EFldL1ug0Mcz4ITOMHeAVjeIFz9hicERUg5ix1NyU7ftt9b6RmPBKBYXLfIHGtbYxhpCdJwfP837Fu6oUKEhXrTwJBhl6yYLaaE1aLe0e7Zgabl2BI01AoS46hUAyMG8ABpV2nBm0o8yimXyYS7+R1q5p1HNc3rhLzyJWZZfwqG7ZyDjtpwOJibi8dZMVWBFfmDLPXjAqKHJKunQwIw/ak65BwahX862QzbZpxL3VceQLQzXfRuWftTNZBVed39bcgm7p+qT5eDMRkQDtzYntA0VSUt6ysG3GVHWop7ctXwaKz1YgYt2QUWvx0hXXkUe03RxN6bIGt0a5QrOiNR418tMtyc4qwIk0PrXMR4V1+38COxiMJ+oUUiz0SjZ5h2z9l6mB3F44Vsr7df8qrhCMu4TABh8OVgd1YVgpz+wGmOLZaHwJGZ6RjlyvRjA8oFAvfwxSMEp+aEjwNWI2h012nBHu209gyG2XdKLY4vgV/RYxEA4qy7c8AWrwOaFx5+CVNWpwF7Um5bhENLnxpewDvJc1jUP+oi1vXZ8Hv/ynLZosmpJgwj4xouxPYA="
arch:
  - amd64
  - arm64
services:
  - docker
script: docker build -t minecraft -f Dockerfile .
